name: Create or Update Solutions File for Daily CSSBattle
on:
  issues:
    types: [opened]

permissions:
  contents: write
  issues: write
  
jobs:
  process-solutions-file:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.title, '[CSSBattle]') || contains(github.event.issue.title, '[CSSBattle-UPDATE]')
    
    env:
      GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
      GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
    
    steps:
      - name: 🔧 Setup Environment
        run: |
          echo "🔍 Workflow Trigger Analysis"
          echo "Issue title: '${{ github.event.issue.title }}'"
          echo "Issue number: ${{ github.event.issue.number }}"
          echo "Repository: ${{ github.repository }}"
          echo ""
          
          # Determine operation type
          if [[ "${{ github.event.issue.title }}" == *"[CSSBattle-UPDATE]"* ]]; then
            echo "OPERATION_TYPE=update" >> $GITHUB_ENV
            echo "✅ Operation: UPDATE"
          else
            echo "OPERATION_TYPE=create" >> $GITHUB_ENV
            echo "✅ Operation: CREATE"
          fi

      - name: 📥 Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: 🛠️ Install Dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y jq file
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          echo "✅ Dependencies installed"

      - name: 📄 Extract Issue Content
        run: |
          echo "📄 Extracting issue body..."
          
          # Save issue body safely
          cat > issue_body.txt << 'ISSUE_EOF'
          ${{ github.event.issue.body }}
          ISSUE_EOF
          
          # Validate content
          if [ ! -s issue_body.txt ]; then
            echo "❌ ERROR: Issue body is empty"
            exit 1
          fi
          
          echo "✅ Issue content extracted ($(wc -l < issue_body.txt) lines)"
          
          # Show structure for debugging
          echo "📋 Issue sections found:"
          grep "^###" issue_body.txt || echo "No sections found"

      - name: 📅 Parse Date
        run: |
          echo "📅 Parsing date from issue..."
          
          # Try multiple date formats
          DATE=""
          
          # Method 1: Month Day, Year (e.g., "Jun 9, 2025")
          DATE=$(grep -oE "(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec|January|February|March|April|May|June|July|August|September|October|November|December)[[:space:]]+[0-9]{1,2},[[:space:]]*[0-9]{4}" issue_body.txt | head -1)
          
          # Method 2: Numeric format (e.g., "6/9/2025")
          if [ -z "$DATE" ]; then
            DATE=$(grep -oE "[0-9]{1,2}/[0-9]{1,2}/[0-9]{4}" issue_body.txt | head -1)
          fi
          
          # Method 3: ISO format (e.g., "2025-06-09")
          if [ -z "$DATE" ]; then
            DATE=$(grep -oE "[0-9]{4}-[0-9]{2}-[0-9]{2}" issue_body.txt | head -1)
          fi
          
          if [ -z "$DATE" ]; then
            echo "❌ ERROR: No date found in issue"
            exit 1
          fi
          
          echo "🔍 Raw date found: '$DATE'"
          
          # Convert to YYYY-MM-DD format
          if FORMATTED_DATE=$(date -d "$DATE" +%Y-%m-%d 2>/dev/null); then
            echo "FORMATTED_DATE=$FORMATTED_DATE" >> $GITHUB_ENV
            echo "✅ Date parsed: $FORMATTED_DATE"
          else
            echo "❌ ERROR: Could not parse date: '$DATE'"
            exit 1
          fi

      - name: 🎨 Extract CSS Content
        run: |
          echo "🎨 Extracting CSS content..."
          
          # Find CSS section
          CSS_START=$(grep -n "### CSS Solution" issue_body.txt | head -1 | cut -d: -f1)
          
          if [ -z "$CSS_START" ]; then
            echo "❌ ERROR: No CSS Solution section found"
            exit 1
          fi
          
          echo "🔍 CSS section starts at line: $CSS_START"
          
          # Find next section
          CSS_END=$(tail -n +$((CSS_START + 1)) issue_body.txt | grep -n "^### " | head -1 | cut -d: -f1)
          
          if [ -n "$CSS_END" ]; then
            ACTUAL_END=$((CSS_START + CSS_END - 1))
            sed -n "$((CSS_START + 1)),$((ACTUAL_END - 1))p" issue_body.txt > css_raw.txt
          else
            tail -n +$((CSS_START + 1)) issue_body.txt > css_raw.txt
          fi
          
          # Clean CSS content
          sed -e '/^[[:space:]]*$/d' \
              -e '/^```css$/d' \
              -e '/^```$/d' \
              -e '/^### /d' \
              -e '/^- \[/d' \
              -e '/^\[x\]/d' \
              -e '/Confirmation/d' \
              css_raw.txt > css_content.txt
          
          if [ ! -s css_content.txt ]; then
            echo "❌ ERROR: No CSS content found after cleaning"
            exit 1
          fi
          
          # Count versions
          VERSION_COUNT=$(grep -c "---VERSION---" css_content.txt || echo 0)
          VERSION_COUNT=$((VERSION_COUNT + 1))
          echo "CSS_VERSION_COUNT=$VERSION_COUNT" >> $GITHUB_ENV
          
          echo "✅ CSS extracted: $VERSION_COUNT version(s), $(wc -l < css_content.txt) lines"

      - name: 🖼️ Find Images
        run: |
          echo "🖼️ Looking for images..."
          
          # Enhanced image URL extraction
          > image_urls.txt
          
          echo "🔍 Searching for various image URL patterns..."
          
          # Pattern 1: Markdown image syntax ![alt](url)
          grep -oE '!\[[^\]]*\]\([^)]+\)' issue_body.txt | sed 's/!\[[^\]]*\](\([^)]*\))/\1/' >> image_urls.txt 2>/dev/null || true
          
          # Pattern 2: HTML img tags <img src="url">
          grep -oE '<img[^>]+src="[^"]*"' issue_body.txt | sed 's/.*src="\([^"]*\)".*/\1/' >> image_urls.txt 2>/dev/null || true
          
          # Pattern 3: GitHub user-images (most common)
          grep -oE 'https://user-images\.githubusercontent\.com/[^[:space:]")\]]+' issue_body.txt >> image_urls.txt 2>/dev/null || true
          
          # Pattern 4: GitHub assets URLs
          grep -oE 'https://github\.com/[^/]+/[^/]+/assets/[^[:space:]")\]]+' issue_body.txt >> image_urls.txt 2>/dev/null || true
          
          # Pattern 5: Any GitHub content URLs
          grep -oE 'https://[^[:space:]")\]]*\.githubusercontent\.com/[^[:space:]")\]]+' issue_body.txt >> image_urls.txt 2>/dev/null || true
          
          # Pattern 6: Direct image URLs with extensions
          grep -oE 'https://[^[:space:]")\]]+\.(png|jpg|jpeg|gif|webp|PNG|JPG|JPEG|GIF|WEBP)' issue_body.txt >> image_urls.txt 2>/dev/null || true
          
          # Show what we found (before deduplication)
          echo "🔍 Raw URLs found:"
          cat image_urls.txt | head -10
          
          # Remove duplicates and filter valid URLs
          if [ -s image_urls.txt ]; then
            # Clean URLs and remove duplicates
            sort image_urls.txt | uniq | grep -E '^https://' | head -20 > image_urls_clean.txt 2>/dev/null || true
            mv image_urls_clean.txt image_urls.txt 2>/dev/null || true
            
            IMAGE_COUNT=$(wc -l < image_urls.txt 2>/dev/null || echo 0)
            echo "✅ Found $IMAGE_COUNT unique image URL(s)"
            echo "IMAGE_COUNT=$IMAGE_COUNT" >> $GITHUB_ENV
            
            # Show final URLs
            if [ "$IMAGE_COUNT" -gt 0 ]; then
              echo "📋 Final image URLs:"
              cat image_urls.txt
            fi
          else
            echo "ℹ️ No images found in issue"
            echo "IMAGE_COUNT=0" >> $GITHUB_ENV
          fi
          
          # Debug: Show markdown image syntax found
          echo "🔍 Markdown images found:"
          grep -E '!\[[^\]]*\]\([^)]+\)' issue_body.txt || echo "No markdown images found"
          
          # Debug: Show HTML img tags found
          echo "🔍 HTML img tags found:"
          grep -E '<img[^>]+src=' issue_body.txt || echo "No HTML img tags found"

      - name: 📁 Create Directory Structure
        run: |
          echo "📁 Creating directory structure..."
          
          if [ -z "$FORMATTED_DATE" ]; then
            echo "❌ ERROR: FORMATTED_DATE not set!"
            echo "Available environment variables:"
            env | grep -E "(FORMATTED_DATE|CSS_VERSION_COUNT|IMAGE_COUNT)" || echo "None found"
            exit 1
          fi
          
          TARGET_DIR="daily-targets/$FORMATTED_DATE"
          mkdir -p "$TARGET_DIR"
          
          if [ ! -d "$TARGET_DIR" ]; then
            echo "❌ ERROR: Failed to create directory: $TARGET_DIR"
            exit 1
          fi
          
          echo "TARGET_DIR=$TARGET_DIR" >> $GITHUB_ENV
          echo "✅ Created directory: $TARGET_DIR"
          
          # Verify directory exists
          ls -la "daily-targets/" || echo "daily-targets directory not found"
          ls -la "$TARGET_DIR" || echo "Target directory empty"

      - name: 📝 Generate Solutions File
        run: |
          echo "📝 Generating solutions.html..."
          
          SOLUTIONS_FILE="$TARGET_DIR/solutions.html"
          
          # Start with Version 1
          echo "<!-- Version 1 -->" > "$SOLUTIONS_FILE"
          
          # Process CSS content
          version_num=1
          while IFS= read -r line || [ -n "$line" ]; do
            if [[ "$line" == "---VERSION---" ]]; then
              echo "</style>" >> "$SOLUTIONS_FILE"
              echo "" >> "$SOLUTIONS_FILE"
              version_num=$((version_num + 1))
              echo "<!-- Version $version_num -->" >> "$SOLUTIONS_FILE"
            else
              echo "$line" >> "$SOLUTIONS_FILE"
            fi
          done < css_content.txt
          
          # Ensure proper closing
          if ! tail -n1 "$SOLUTIONS_FILE" | grep -q "</style>"; then
            echo "</style>" >> "$SOLUTIONS_FILE"
          fi
          
          echo "✅ Solutions file created with $CSS_VERSION_COUNT version(s)"

      - name: 🖼️ Download Images
        run: |
          echo "🖼️ Processing images..."
          
          if [ "$IMAGE_COUNT" = "0" ]; then
            echo "ℹ️ No images found in issue body"
            echo "DOWNLOADED_COUNT=0" >> $GITHUB_ENV
          else
            echo "🖼️ Downloading $IMAGE_COUNT image(s)..."
            
            counter=1
            while IFS= read -r img_url; do
              if [ -n "$img_url" ]; then
                # Get file extension
                ext=$(echo "$img_url" | grep -oE '\.(png|jpg|jpeg|gif|webp)' | head -1)
                [ -z "$ext" ] && ext=".png"
                
                filename="target-${counter}-comparison${ext}"
                filepath="$TARGET_DIR/$filename"
                
                echo "📥 Downloading: $filename"
                echo "    URL: $img_url"
                
                # Simple download with timeout
                if curl -L -f -s --max-time 30 "$img_url" -o "$filepath" 2>/dev/null; then
                  if [ -s "$filepath" ]; then
                    echo "✅ Downloaded: $filename ($(du -h "$filepath" | cut -f1))"
                    counter=$((counter + 1))
                  else
                    echo "❌ Downloaded file is empty: $filename"
                    rm -f "$filepath"
                  fi
                else
                  echo "❌ Failed to download: $img_url"
                fi
              fi
            done < image_urls.txt
            
            DOWNLOADED_COUNT=$((counter - 1))
            echo "DOWNLOADED_COUNT=$DOWNLOADED_COUNT" >> $GITHUB_ENV
            echo "✅ Downloaded $DOWNLOADED_COUNT of $IMAGE_COUNT images"
          fi

      - name: 📱 Generate LinkedIn Post
        run: |
          echo "📱 Generating LinkedIn post..."
          
          # Extract additional notes
          NOTES=$(sed -n '/### Additional Notes/,/### Confirmation/p' issue_body.txt | \
                  sed '/### Additional Notes/d; /### Confirmation/,$d; /^[[:space:]]*$/d; /^- \[/d' | \
                  head -3 | tr '\n' ' ' | xargs)
          
          # Use default if no notes found
          [ -z "$NOTES" ] && NOTES="Another CSS challenge completed! 🎯"
          
          # Generate post
          LINKEDIN_FILE="$TARGET_DIR/linkedin-post.md"
          SOLUTIONS_URL="https://github.com/${{ github.repository }}/blob/main/$TARGET_DIR/solutions.html"
          
          # Create LinkedIn post using echo (safer than heredoc)
          echo "# LinkedIn Post for $FORMATTED_DATE" > "$LINKEDIN_FILE"
          echo "" >> "$LINKEDIN_FILE"
          echo "---" >> "$LINKEDIN_FILE"
          echo "" >> "$LINKEDIN_FILE"
          echo "Today's CSSBattle solution:" >> "$LINKEDIN_FILE"
          echo "" >> "$LINKEDIN_FILE"
          echo "$NOTES" >> "$LINKEDIN_FILE"
          echo "" >> "$LINKEDIN_FILE"
          echo "$SOLUTIONS_URL" >> "$LINKEDIN_FILE"
          echo "" >> "$LINKEDIN_FILE"
          echo "(My journal notes.)" >> "$LINKEDIN_FILE"
          echo "" >> "$LINKEDIN_FILE"
          echo "#cssgang #CSS #CSSBattle #HTML" >> "$LINKEDIN_FILE"
          
          # Verify file was created
          if [ -f "$LINKEDIN_FILE" ]; then
            echo "✅ LinkedIn post generated"
            echo "📄 Content preview:"
            head -5 "$LINKEDIN_FILE"
          else
            echo "❌ Failed to create LinkedIn post"
            exit 1
          fi

      - name: 🔄 Commit and Push Changes
        run: |
          echo "🔄 Committing changes..."
          
          # Configure Git
          git config --local user.email "${GIT_USER_EMAIL:-${{ github.actor }}@users.noreply.github.com}"
          git config --local user.name "${GIT_USER_NAME:-${{ github.actor }}}"
          
          # Show what files exist
          echo "📋 Files in repository:"
          find . -name "*.html" -o -name "*.md" | grep daily-targets || echo "No daily-targets files found"
          
          # Add files
          git add .
          
          # Show what's staged
          echo "📋 Files staged for commit:"
          git diff --staged --name-only || echo "No files staged"
          
          # Check for changes
          if git diff --staged --quiet; then
            echo "ℹ️ No changes to commit"
            echo "HAS_CHANGES=false" >> $GITHUB_ENV
          else
            echo "📝 Changes detected, proceeding with commit..."
            
            # Show what will be committed
            git diff --staged --stat
            
            # Commit
            COMMIT_MSG="feat: CSS Battle solution for $FORMATTED_DATE"
            git commit -m "$COMMIT_MSG"
            
            # Push with retry
            for i in {1..3}; do
              if git push origin main; then
                echo "✅ Changes pushed successfully"
                echo "HAS_CHANGES=true" >> $GITHUB_ENV
                break
              else
                echo "❌ Push attempt $i failed"
                [ $i -lt 3 ] && sleep 2
              fi
            done
            
            if [ "$i" = "3" ] && ! git push origin main; then
              echo "❌ All push attempts failed"
              echo "HAS_CHANGES=false" >> $GITHUB_ENV
            fi
          fi

      - name: ✅ Create Success Comment
        if: env.HAS_CHANGES == 'true'
        run: |
          echo "✅ Creating success comment..."
          
          # Calculate character count
          CHAR_COUNT=$(sed 's|</style>||g' css_content.txt | tr -d '\n' | wc -c)
          
          # Create comment using echo (safer than heredoc)
          cat > comment.txt << 'COMMENT_EOF'
# ✅ CSS Battle Solution Processed Successfully!

## 📁 Location
`$TARGET_DIR/`

## 📊 Summary
- 🎯 **CSS Versions:** $CSS_VERSION_COUNT
- 🖼️ **Images Found:** ${IMAGE_COUNT:-0}
- 📥 **Images Downloaded:** ${DOWNLOADED_COUNT:-0}
- ⚡ **Character Count:** $CHAR_COUNT chars
- 📅 **Date:** $FORMATTED_DATE

## 📄 Files Created
- ✅ `solutions.html` - Your CSS solution
- ✅ `linkedin-post.md` - Ready-to-post content

## 🔗 Quick Links
- 💻 **[View Solution](${{ github.server_url }}/${{ github.repository }}/blob/main/$TARGET_DIR/solutions.html)**
- 📱 **[LinkedIn Post](${{ github.server_url }}/${{ github.repository }}/blob/main/$TARGET_DIR/linkedin-post.md)**
- 📁 **[Full Directory](${{ github.server_url }}/${{ github.repository }}/tree/main/$TARGET_DIR)**

## 🎉 Ready for Battle!
Your solution is organized and ready for sharing!

---
*✨ Processed by GitHub Actions*
COMMENT_EOF
          
          # Post comment and close issue
          gh issue comment "${{ github.event.issue.number }}" --body-file comment.txt
          gh issue close "${{ github.event.issue.number }}" --reason completed
          
          echo "✅ Issue processed and closed"

      - name: 🧹 Cleanup
        if: always()
        run: |
          echo "🧹 Cleaning up temporary files..."
          
          # Remove temporary files
          rm -f issue_body.txt css_raw.txt css_content.txt image_urls.txt comment.txt
          
          echo "✅ Cleanup completed"
